display_name: Veil

icon: ./assets/images/icon.png

supported_mime_type:
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/veil

keywords:
  - Veil
  - Clash
  - ClashMeta
  - Proxy

generic_name: Veil

categories:
  - Network

startup_notify: true

include: []